### PR TITLE
Restrict access

### PR DESCRIPTION
**Pull request by RafaelOstertag**
All access restricted. @e-i-n-s or @mawit please test.

### CODE REVIEW

**Comment by e-i-n-s** [comment]
I can't login with the global admin:

Trace:
017-05-17 20:13:07.862 ERROR 16976 --- [nio-8080-exec-9] c.z.p.security.web.StatelessLoginFilter  : An internal error occurred while trying to authenticate the user.

Response to login http-request:
"Authentication Failed: failed to lazily initialize a collection of role: ch.zhaw.psit4.data.jpa.entities.Admin.company, could not initialize proxy - no Session"

**Comment by RafaelOstertag** [comment]
@e-i-n-s Same here. Will take care of it tomorrow.

**Comment by RafaelOstertag** [comment]
@e-i-n-s  Commit 0292839 should fix the login issue.

**Comment by e-i-n-s** [comment]
Great work!

**Pull request merged**
